module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  mode: "jit",
  theme: {
    screens: {
      md: "640px",
      lg: "1024px",
      xl: "1280px",
      sxl: "1440px",
    },
    color: {
      thumb: "#6C3AC2",
      track: "#666666",
    },
    fontSize: {
      h1: "36px",
      h2: "24px",
      h3: "18px",
      h4: "16px",
      p: "14px",
      "mobile-h1": "23px",
      "mobile-h2": "21px",
      "mobile-h3": "20px",
      "mobile-h4": "17px",
      "mobile-h5": "15px",
      "mobile-p1": "13px",
      "mobile-s": "11px",
      "mobile-xs": "7px",
      "laptop-h1": "24px",
      "laptop-h2": "22px",
      "laptop-h3": "18px",
      "tablet-h4": "18px",
      "tablet-h5": "16px",
      "tablet-p1": "14px",
      "tablet-s": "12px",
      "tablet-xs": "8px",
    },
    extend: {
      fontFamily: {
        montserrat: ["Montserrat", "san-serif"],
      },
      textColor: {
        "heading-false": "#4f4d4e",
        heading: "#000000",
        "tertiary-yellow": "#ffac3f",
        "secondary-light": "#908f8f",
        "primary-white": "#ffffff",
        "primary-light": "#fffffb",
        "primary-dark": "#515151",
        "tertiary-red": "#da4747",
        "light-green": "#4cd964",
      },
      backgroundColor: {
        "primary-white": "#ffffff",
        "primary-dark": "#515151",
        "secondary-light": "#908f8f",
        "tertiary-yellow": "#ffac3f",
        "primary-light": "#fffffb",
        "light-gray": "#dfdfdf",
        "light-green": "#4cd964",
        "light-blue": "#d8f7fb",
      },
      borderColor: {
        "tertiary-yellow": "#ffac3f",
        "primary-light": "#fffffb",
        "secondary-purple": "#6c3ac2",
      },
      borderWidth: {},
      width: {
        321: "321px",
        431: "431px",
        search: "560px",
        "pop-up": "532px",
        sidebar: "90px",
        "filter-popUP": "302px",
      },
      height: {
        "pop-up": "360px",
        sidebar: "420px",
        "filter-popUP": "292px",
        128: "100vh",
      },
      spacing: {
        128: "40rem",
      },
      outlineColor: {
        "primary-light": "#F8BD7A",
      },
      colors: {
        "tertiary-yellow": "#ffac3f",
      },
      dropShadow: {
        sm: "0px 0px 8px rgba(0, 0, 0, 0.14)",
      },
    },
  },
  plugins: [],
};
